Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -15,28 +15,24 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    outputs:
-        ssh: ${{ steps.ssh.outputs.test }}
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
+    outputs:
+      ssh-output: ${{ steps.ssh.outputs.output }}
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Auth
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           ID_RSA: ${{ secrets.ID_RSA }}
         run: |
-           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
-           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
-           aws configure set region us-east-1
-           IP=`curl -s http://whatismyip.akamai.com/`
-           echo $IP
-           aws ec2 authorize-security-group-ingress --group-name "launch-wizard-3" --protocol tcp --port 33018 --cidr $IP/32 --profile default --output text
+          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
+          aws configure set region us-east-1
+          IP=$(curl -s http://whatismyip.akamai.com/)
+          echo "::set-output name=ip::$IP"
+          aws ec2 authorize-security-group-ingress --group-name "launch-wizard-3" --protocol tcp --port 33018 --cidr $IP/32 --profile default --output text
 
       - name: SSH
         id: ssh
@@ -46,13 +42,14 @@ jobs:
           username: admin
           port: 33018
           key: ${{ secrets.ID_RSA }}
-          script: build test -s
+          script: |
+            output=$(build test -s)
+            echo "$output"
+            if echo "$output" | grep -qi "fail"; then
+              echo "Error: SSH command output contains 'fail'."
+              exit 1
+            fi
 
-          
-  result:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - env: 
-          OUTPUT: ${{ needs.build.outputs.ssh }}
-        run: echo "$OUTPUT"
+      - name: Use SSH Output
+        run: echo "The SSH output was ${{ needs.build.outputs.ssh-output }}"
+
